# Generated by Django 4.1.3 on 2022-12-09 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("twitter_clone", "0002_hashtag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hashtag",
            name="name",
            field=models.TextField(unique=True),
        ),
    ]
